---
name: Bug Report
about: Create a report to help us improve Matrix Language
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees: ''

---

## Bug Description
A clear and concise description of what the bug is.

## Steps to Reproduce
Steps to reproduce the behavior:
1. Create a file with content '...'
2. Run command '...'
3. See error

## Expected Behavior
A clear and concise description of what you expected to happen.

## Actual Behavior
A clear and concise description of what actually happened.

## Code Sample
```matrix
// Please provide a minimal code sample that reproduces the issue
let example = "your code here"
```

## Environment Information
- **OS**: [e.g. Ubuntu 22.04, Windows 11, macOS 13]
- **Rust Version**: [output of `rustc --version`]
- **Matrix Language Version**: [output of `matrix-lang --version`]
- **Installation Method**: [cargo install, built from source, etc.]

## Error Output
```
Paste any error messages, stack traces, or relevant output here
```

## Additional Context
Add any other context about the problem here, such as:
- Does this happen consistently or intermittently?
- Did this work in a previous version?
- Are there any workarounds?
- Screenshots if applicable

## Checklist
- [ ] I have searched existing issues to ensure this bug hasn't been reported before
- [ ] I have provided a minimal code sample that reproduces the issue
- [ ] I have included my environment information
- [ ] I have included any relevant error messages
