name: Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-docs-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-docs-
            ${{ runner.os }}-cargo-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev

      - name: Build documentation
        run: cargo doc --all-features --no-deps --document-private-items

      - name: Check for broken links in docs
        run: cargo doc --all-features --no-deps --document-private-items 2>&1 | grep -i "warn\|error" || true

      - name: Deploy documentation to GitHub Pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          force_orphan: true

  readme:
    name: Check README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install markdown link checker
        run: npm install -g markdown-link-check

      - name: Check links in README
        run: markdown-link-check README.md || echo "Link check completed with warnings"

  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install cspell
        run: npm install -g cspell

      - name: Run spell check on Rust files
        run: |
          find src -name "*.rs" -exec cspell {} \; || echo "Spell check completed with suggestions"

      - name: Run spell check on documentation
        run: |
          cspell README.md || echo "README spell check completed with suggestions"
